export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const PROFILE_REQUEST = "PROFILE_REQUEST";

export const AUTHOR_REQUEST = "AUTHOR_REQUEST";
export const ADD_AUTHOR_REQUEST = "ADD_AUTHOR_REQUEST";
export const UPDATE_AUTHOR_REQUEST = "UPDATE_AUTHOR_REQUEST";
export const REMOVE_AUTHOR_REQUEST = "REMOVE_AUTHOR_REQUEST";

export const BOOK_REQUEST = "BOOK_REQUEST";
export const EDIT_BOOK_REQUEST = "EDIT_BOOK_REQUEST";
export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
